// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkDbWgIVJD57iHOuAkRXBccL19IoTemfc',
    appId: '1:66616397964:web:bb8bdcfc96477f6f34eba9',
    messagingSenderId: '66616397964',
    projectId: 'transport-jobs-mobile-app',
    authDomain: 'transport-jobs-mobile-app.firebaseapp.com',
    storageBucket: 'transport-jobs-mobile-app.appspot.com',
    measurementId: 'G-QEWCGQYL77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKAL5duS4lkmqNrf6sZadWxAx1XB9CfEs',
    appId: '1:66616397964:android:61793b82388b61f934eba9',
    messagingSenderId: '66616397964',
    projectId: 'transport-jobs-mobile-app',
    storageBucket: 'transport-jobs-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW9ZBodACQp7Mz0OCqsTnBwJ_Bg84hlnw',
    appId: '1:66616397964:ios:ec79c286a4d1932934eba9',
    messagingSenderId: '66616397964',
    projectId: 'transport-jobs-mobile-app',
    storageBucket: 'transport-jobs-mobile-app.appspot.com',
    iosClientId: '66616397964-6skqlurebjfctj0dodojj5c2rlua0eni.apps.googleusercontent.com',
    iosBundleId: 'com.example.index2',
  );
}
